export const products = [
  {
    id: "1",
    name: "Wireless Noise-Cancelling Headphones",
    price: 299.99,
    currency: "USD",
    description: "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and Hi-Res audio support.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Headphones",
    rating: 4.7,
    inStock: true,
    category: "Electronics",
    url: "#",
  },
  {
    id: "2",
    name: "Ergonomic Mechanical Keyboard",
    price: 179.99,
    currency: "USD",
    description: "Split ergonomic design with hot-swappable Cherry MX switches, RGB backlighting, and programmable keys.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Keyboard",
    rating: 4.5,
    inStock: true,
    category: "Electronics",
    url: "#",
  },
  {
    id: "3",
    name: "Ultra-Slim Laptop Stand",
    price: 49.99,
    currency: "USD",
    description: "Adjustable aluminum laptop stand with cable management, compatible with laptops up to 17 inches.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Stand",
    rating: 4.8,
    inStock: true,
    category: "Accessories",
    url: "#",
  },
  {
    id: "4",
    name: "Smart Fitness Watch Pro",
    price: 399.99,
    currency: "USD",
    description: "Advanced health monitoring with ECG, SpO2, sleep tracking, and 7-day battery life. Water resistant to 50m.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Watch",
    rating: 4.6,
    inStock: false,
    category: "Wearables",
    url: "#",
  },
  {
    id: "5",
    name: "Portable Bluetooth Speaker",
    price: 129.99,
    currency: "USD",
    description: "360-degree sound with deep bass, IP67 waterproof rating, and 20-hour playtime.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Speaker",
    rating: 4.4,
    inStock: true,
    category: "Electronics",
    url: "#",
  },
  {
    id: "6",
    name: "USB-C Hub Docking Station",
    price: 89.99,
    currency: "USD",
    description: "12-in-1 hub with dual HDMI, USB 3.0 ports, SD card reader, Ethernet, and 100W power delivery.",
    image: "https://placehold.co/300x300/f59e0b/fff?text=Hub",
    rating: 4.3,
    inStock: true,
    category: "Accessories",
    url: "#",
  },
];

export const projects = [
  {
    id: "1",
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce platform with real-time inventory, payment processing, and admin dashboard.",
    image: "https://placehold.co/600x400/7c3aed/fff?text=E-Commerce",
    technologies: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
    status: "completed" as const,
    url: "#",
  },
  {
    id: "2",
    title: "AI Content Generator",
    description: "AI-powered content generation tool for marketing teams with multi-language support and brand voice training.",
    image: "https://placehold.co/600x400/7c3aed/fff?text=AI+Tool",
    technologies: ["React", "Python", "OpenAI", "FastAPI"],
    status: "completed" as const,
    url: "#",
  },
  {
    id: "3",
    title: "Real-Time Analytics Dashboard",
    description: "Live analytics dashboard with customizable widgets, data visualization, and automated reporting.",
    image: "https://placehold.co/600x400/7c3aed/fff?text=Dashboard",
    technologies: ["Vue.js", "D3.js", "WebSocket", "Redis"],
    status: "completed" as const,
    url: "#",
  },
  {
    id: "4",
    title: "Mobile Banking App",
    description: "Secure mobile banking application with biometric auth, instant transfers, and financial insights.",
    image: "https://placehold.co/600x400/7c3aed/fff?text=Banking",
    technologies: ["React Native", "Node.js", "MongoDB", "AWS"],
    status: "in-progress" as const,
    url: "#",
  },
];

export const portfolioOwner = {
  name: "Awadhesh Kumar",
  bio: "Senior Full-Stack Developer with 8+ years of experience building scalable web applications. Passionate about AI/ML, cloud architecture, and developer experience.",
  skills: [
    "TypeScript", "React", "Next.js", "Node.js", "Python",
    "PostgreSQL", "Redis", "AWS", "Docker", "GraphQL",
  ],
  email: "alex@example.com",
  github: "https://github.com/alexjohnson",
  linkedin: "https://linkedin.com/in/alexjohnson",
};
